FuNDs/FuNDs/Controllers/CampaignsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FuNDs.Models;
using Microsoft.AspNet.Identity;

using System.Web.Services;

namespace FuNDs.Controllers
{
    public class CampaignsController : Controller
    {
        private FundRaisersDbContext db = new FundRaisersDbContext();

        public ActionResult Index()
        {
            int x = Convert.ToInt32(Session["userId"]);


            var user = db.FundRaisers.FirstOrDefault(s => s.FundRaisersId == x);

            if (user != null && user.Campaigns!= null)
            {
                List<Campaign> campaignlist = new List<Campaign>();
                foreach (var campaign in user.Campaigns)
                {
                    campaignlist.Add(campaign);
                }

                return View(campaignlist.ToList());
            }
            else
            {
                ModelState.AddModelError("doesUserExist", "Email Not verified. Please check your email confirmation");
                return View("Index", "Home");
            }

        }

        

        public ActionResult AllCampaigns(string sortOrder, string searchString)
        {
            // public ViewResult Index(string sortOrder, string searchString)

            if (!String.IsNullOrEmpty(searchString))
            {

                ViewBag.CurrentSort = sortOrder;
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                // ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

                var campaigns = from s in db.Campaigns
                                select s;

                if (!String.IsNullOrEmpty(searchString))
                {
                    campaigns = campaigns.Where(s => s.CampaignTitle.ToUpper().Contains(searchString.ToUpper()));
                                          
                }

                // campaigns = campaigns.Where(s => s.CampaignTitle.Contains(searchString));

                switch (sortOrder)
                {
                    case "Name_desc":
                        campaigns = campaigns.OrderByDescending(s => s.CampaignTitle);
                        break;
                    //case "Date":
                    //    campaigns = campaigns.OrderBy(s => s.StartingDate);
                    //    break;
                    //case "Date_desc":
                    //    campaigns = campaigns.OrderByDescending(s => s.StartingDate);
                    //    break;
                    //default:
                    //    campaigns = campaigns.OrderBy(s => s.CampaignTitle);
                    //    break;
                }
                return View("AllCampaigns", campaigns.ToList());
            }
            //  return View("SearchResults", projects.ToList());
            else
            {
                
                List<Campaign> allCampaigns = new List<Campaign>();

                allCampaigns = db.Campaigns.ToList();
                return View(allCampaigns);
            }
        }
            
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = db.Campaigns.Find(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            return View(campaign);
        }

        // GET: Campaigns/Create
        public ActionResult Create()
        {
            ViewBag.FundRaisersId = new SelectList(db.FundRaisers, "ID", "FirstName");
            return View();
        }

        // POST: Campaigns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CampaignId,CampaignTitle,CampaignDescription,CampaignAmount,startingDate,endingDate,FundRaisersId")] Campaign campaign)
        {
            if (ModelState.IsValid)
            {
                Session["CampaignId"] = campaign.CampaignId;
                campaign.FundRaisersId = Convert.ToInt32(Session["userId"]);
                db.Campaigns.Add(campaign);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FundRaisersId = new SelectList(db.FundRaisers, "ID", "FirstName", campaign.FundRaisersId);
            return View(campaign);
        }

        // GET: Campaigns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = db.Campaigns.Find(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            ViewBag.FundRaisersId = new SelectList(db.FundRaisers, "ID", "FirstName", campaign.FundRaisersId);
            return View(campaign);
        }

        // POST: Campaigns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CampaignId,CampaignTitle,CampaignDescription,CampaignAmount,startingDate,endingDate,FundRaisersId")] Campaign campaign)
        {
            if (ModelState.IsValid)
            {
                db.Entry(campaign).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FundRaisersId = new SelectList(db.FundRaisers, "ID", "FirstName", campaign.FundRaisersId);
            return View(campaign);
        }

        // GET: Campaigns/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = db.Campaigns.Find(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            return View(campaign);
        }

        // POST: Campaigns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Campaign campaign = db.Campaigns.Find(id);
            db.Campaigns.Remove(campaign);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FuNDs/FuNDs/Views/layout/layout.cshtml
 
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CONVERGENT</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/Content/custom.css" />
    @*<link rel="stylesheet" href="~/Content/Site.css">*@
    @*Styles.Render("~/Content/css")*@

</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--<a class="navbar-brand" href="/Home"><img src="~/Content/Images/Untitled-1.png" alt="Convergent"></a>-->
                <a class="navbar-brand" href="/Home"><img src="~/Content/Images/Untitled-1.png" alt="Convergent"></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


                <div class="navbar-form navbar-right" role="search" style="padding-left:35px;">
                    <p>
                        @using (Html.BeginForm("AllCampaigns", "Campaigns", FormMethod.Get))
                        {
                        <p>
                            <div class="form-group">
                                @Html.TextBox("SearchString")
                                <input type="submit" class="btn btn-default" />
                            </div>
                        </p>
                        }
                        </p>

                    </div>

                    @*<form class="navbar-form navbar-right" role="search" action="/Campaigns/AllCampaigns" method="POST">

                            }
                             <p>
                                @using (Html.BeginForm("AllCampaigns", "Campaigns", FormMethod.Get))
                                {
                                <p>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </form>*@

                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.Partial("_LoginPartial")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-left">


                        <li>@Html.ActionLink("How it works", "HowItWorks", "Home")</li>
                        <li>@Html.ActionLink("Start a Campaign", "Create", "Campaigns")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>

        <div class="body-content">

            @RenderBody()

        </div>

        <nav class="navbar navbar-default navbar-fixed-bottom">
            <div class="container text-center">
                <h5 class="text-center">&copy; @DateTime.Now.Year - Team Origin </h5>
            </div>
        </nav>
        <!-- /.container-fluid -->


        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>