FuNDs/FuNDs/Models/Campaign.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FuNDs.Models
{
    public class Campaign
    {
        
        public int CampaignId { get; set; }

        public string CampaignTitle { get; set; }
        public string CampaignDescription { get; set; }

        public double CampaignAmount { get; set; }

        [Column(TypeName ="datetime2")]
        public DateTime? StartingDate { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime? EndingDate { get; set; }


        [Display(Name = "FundRaisers*")]
        [Required(ErrorMessage = "Who is the fundRaiserss")]
       
        public int FundRaisersId { get; set; }


        public virtual FundRaisers FundRaisers { get; set; }

        public virtual ICollection<Donor> donateAmount { get; set; }
    }
}

FuNDs/FuNDs/Controllers/CampaignsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FuNDs.Models;
using Microsoft.AspNet.Identity;

using System.Web.Services;

namespace FuNDs.Controllers
{
    public class CampaignsController : Controller
    {
        private FundRaisersDbContext db = new FundRaisersDbContext();

        public ActionResult Index()
        {
            int x = Convert.ToInt32(Session["userId"]);


            var user = db.FundRaisers.FirstOrDefault(s => s.FundRaisersId == x);

            if (user != null && user.Campaigns!= null)
            {
                List<Campaign> campaignlist = new List<Campaign>();
                foreach (var campaign in user.Campaigns)
                {
                    campaignlist.Add(campaign);
                }

                return View(campaignlist.ToList());
            }
            else
            {
                ModelState.AddModelError("doesUserExist", "Email Not verified. Please check your email confirmation");
                return View("Index", "Home");
            }

        }

        

        public ActionResult AllCampaigns(string sortOrder, string searchString)
        {
            // public ViewResult Index(string sortOrder, string searchString)

            if (!String.IsNullOrEmpty(searchString))
            {

                ViewBag.CurrentSort = sortOrder;
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                // ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

                var campaigns = from s in db.Campaigns
                                select s;

                if (!String.IsNullOrEmpty(searchString))
                {
                    campaigns = campaigns.Where(s => s.CampaignTitle.ToUpper().Contains(searchString.ToUpper()));
                                          
                }

                // campaigns = campaigns.Where(s => s.CampaignTitle.Contains(searchString));

                switch (sortOrder)
                {
                    case "Name_desc":
                        campaigns = campaigns.OrderByDescending(s => s.CampaignTitle);
                        break;
                    //case "Date":
                    //    campaigns = campaigns.OrderBy(s => s.StartingDate);
                    //    break;
                    //case "Date_desc":
                    //    campaigns = campaigns.OrderByDescending(s => s.StartingDate);
                    //    break;
                    //default:
                    //    campaigns = campaigns.OrderBy(s => s.CampaignTitle);
                    //    break;
                }
                return View("AllCampaigns", campaigns.ToList());
            }
            //  return View("SearchResults", projects.ToList());
            else
            {
                
                List<Campaign> allCampaigns = new List<Campaign>();

                allCampaigns = db.Campaigns.ToList();
                return View(allCampaigns);
            }
        }
            
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = db.Campaigns.Find(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            return View(campaign);
        }

        // GET: Campaigns/Create
        public ActionResult Create()
        {
            ViewBag.FundRaisersId = new SelectList(db.FundRaisers, "ID", "FirstName");
            return View();
        }

        // POST: Campaigns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CampaignId,CampaignTitle,CampaignDescription,CampaignAmount,startingDate,endingDate,FundRaisersId")] Campaign campaign)
        {
            if (ModelState.IsValid)
            {
                Session["CampaignId"] = campaign.CampaignId;
                campaign.FundRaisersId = Convert.ToInt32(Session["userId"]);
                db.Campaigns.Add(campaign);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FundRaisersId = new SelectList(db.FundRaisers, "ID", "FirstName", campaign.FundRaisersId);
            return View(campaign);
        }

        // GET: Campaigns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = db.Campaigns.Find(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            ViewBag.FundRaisersId = new SelectList(db.FundRaisers, "ID", "FirstName", campaign.FundRaisersId);
            return View(campaign);
        }

        // POST: Campaigns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CampaignId,CampaignTitle,CampaignDescription,CampaignAmount,startingDate,endingDate,FundRaisersId")] Campaign campaign)
        {
            if (ModelState.IsValid)
            {
                db.Entry(campaign).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FundRaisersId = new SelectList(db.FundRaisers, "ID", "FirstName", campaign.FundRaisersId);
            return View(campaign);
        }

        // GET: Campaigns/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = db.Campaigns.Find(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            return View(campaign);
        }

        // POST: Campaigns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Campaign campaign = db.Campaigns.Find(id);
            db.Campaigns.Remove(campaign);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FuNDs/FuNDs/Controllers/DonorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FuNDs.Models;

namespace FuNDs.Controllers
{
    public class DonorsController : Controller
    {
        private FundRaisersDbContext db = new FundRaisersDbContext();

        // GET: Donors
        public ActionResult Index()
        {
            return View(db.Donors.ToList());
        }

        // GET: Donors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donor donor = db.Donors.Find(id);
            if (donor == null)
            {
                return HttpNotFound();
            }
            return View(donor);
        }

        // GET: Donors/Create
        public ActionResult Create()
        {
          //  Donor donor = new Donor();
          //  donor.CampaignId = id;
           
            return View();
        }

        

        // POST: Donors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DonorId,donateAmount,donateDate")] Donor donor)
        {

            if (ModelState.IsValid)
            {
                db.Donors.Add(donor);
                db.SaveChanges();
                
            }
            return View("Pay");
        }

        public ActionResult Pay()
        {
            return View();
        }
        // GET: Donors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donor donor = db.Donors.Find(id);
            if (donor == null)
            {
                return HttpNotFound();
            }
            return View(donor);
        }

        // POST: Donors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DonorId,donateAmount,donateDate")] Donor donor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(donor);
        }

        // GET: Donors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donor donor = db.Donors.Find(id);
            if (donor == null)
            {
                return HttpNotFound();
            }
            return View(donor);
        }

        // POST: Donors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Donor donor = db.Donors.Find(id);
            db.Donors.Remove(donor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FuNDs/FuNDs/Views/Campaigns/AllCampaigns.cshtml
@model IEnumerable<FuNDs.Models.Campaign>
@{
    ViewBag.Title = "AllCampaigns";
}

<section id="all-campaigns" class="container">
  

        <div class="container">


            <div class="row">
                @foreach (var item in Model)
    {

            <div class="col-md-4 campaign">

                <div class="row">
                    <div class="col-xs-6">
                        <h4 class="title">

                            @Html.ActionLink(item.CampaignTitle, "Pay","Donors" ,new { id = item.CampaignId}, null)

                        </h4>
                    </div>
                    <div class="col-xs-6">
                        <h4 class="amount text-right">
                            <span class="raised">$0</span><span class="target">/@Html.DisplayFor(modelItem => item.CampaignAmount)</span>
                        </h4>
                    </div>
                </div>


                <p>
                    @Html.DisplayFor(modelItem => item.CampaignDescription)
                </p>
                <hr />


            </div>

    }
            </div>

        </div>
</section>

FuNDs/FuNDs/Views/Campaigns/Create.cshtml
@model FuNDs.Models.Campaign

@{
    ViewBag.Title = "Create";
}

<section class="container" id="campaign-create">

    @if (Request.IsAuthenticated)
    {

        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Campaign</h4>
                <hr />
                
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @*Html.LabelFor(model => model.CampaignTitle, htmlAttributes: new { @class = "control-label col-md-3" })*@
                    <label for="CampaignTitle" class="control-label col-md-3">Campaign Title</label>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.CampaignTitle, new { htmlAttributes = new { @class = "form-control", @placeholder = "eg: Social Club Establishment" } })
                        @Html.ValidationMessageFor(model => model.CampaignTitle, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="CampaignDescription" class="control-label col-md-3">Campaign Description</label>
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.CampaignDescription, new { @class = "form-control", @placeholder = "Write description here...", @rows = "5" })
                        @Html.ValidationMessageFor(model => model.CampaignDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="CampaignAmount" class="control-label col-md-3">Target Amount</label>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.CampaignAmount, new { htmlAttributes = new { @class = "form-control", @placeholder = "eg: 1000" } })
                        @Html.ValidationMessageFor(model => model.CampaignAmount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="StartingDate" class="control-label col-md-3" >Campaign Date</label>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.StartingDate, new { htmlAttributes = new { @class = "form-control" , @placeholder = "eg: 10//11/1995" } })
                        @Html.ValidationMessageFor(model => model.StartingDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="EndingDate" class="control-label col-md-3">Ending Date</label>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.EndingDate, new { htmlAttributes = new { @class = "form-control" , @placeholder = "eg: 10/11/1995" } })
                        @Html.ValidationMessageFor(model => model.EndingDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                        @Html.LabelFor(model => model.FundRaisersId, "FundRaisersId", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.DropDownList("FundRaisersId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.FundRaisersId, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                <div class="form-group">
                    <div class="col-md-12">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    }

    else
    {

        @Html.ActionLink("You are just a step ahead. Sign up first", "Create", "FundRaisers")

    }

</section>

FuNDs/FuNDs/Views/Campaigns/Delete.cshtml
@model FuNDs.Models.Campaign

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Campaign</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FundRaisers.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FundRaisers.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CampaignTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CampaignTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CampaignDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CampaignDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CampaignAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CampaignAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndingDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FuNDs/FuNDs/Views/Campaigns/Details.cshtml
@model FuNDs.Models.Campaign

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Campaign</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FundRaisers.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FundRaisers.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CampaignTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CampaignTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CampaignDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CampaignDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CampaignAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CampaignAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndingDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CampaignId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FuNDs/FuNDs/Views/Campaigns/Edit.cshtml
@model FuNDs.Models.Campaign

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Campaign</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CampaignId)

        <div class="form-group">
            @Html.LabelFor(model => model.CampaignTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CampaignTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CampaignTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CampaignDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CampaignDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CampaignDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CampaignAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CampaignAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CampaignAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FundRaisersId, "FundRaisersId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FundRaisersId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FundRaisersId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FuNDs/FuNDs/Views/Campaigns/Index.cshtml
@model IEnumerable<FuNDs.Models.Campaign>

@{
    ViewBag.Title = "Index";
}

<section id="all-campaigns" class="container">
    <level class="container text-left" style="margin-left:5px;">
        <div class="bs-callout bs-callout-warning">
            <h5>@Html.ActionLink("[Create New Campaign]", "Create")</h5>
        </div>

    </level>

    <div class="container">

        <div class="row">
            @foreach (var item in Model)
            {

                <div class="col-md-4 campaign">

                    <div class="row">
                        <div class="col-xs-6">
                            <h4 class="title">
                                @Html.ActionLink(item.CampaignTitle, "Pay", "Donors", new { id = item.CampaignId }, null)

                            </h4>
                        </div><div class="col-xs-6">
                            <h4 class="amount text-right">
                                <span class="raised">$0</span><span class="target">/@Html.DisplayFor(modelItem => item.CampaignAmount)</span>
                            </h4>
                        </div>
                    </div>


                    <p>
                        @Html.DisplayFor(modelItem => item.CampaignDescription)
                    </p>
                    <hr />
                 
                   
                </div>

            }
        </div>

    </div>
</section>