FuNDs/FuNDs/Models/Donor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FuNDs.Models
{
    public class Donor
    {
        public int DonorId { get; set; }



      //  public string donorFirstName { get; set; }

        //    public string? donorLastName { get; set; }

        public double DonationAmount { get; set; }

        public string donateDate { get; set; }

        /*   public string? donorMessage { get; set; */

            // creating a foreign campaign ID/KEy
      //  public int CampaignId { get; set; }

       // public virtual Campaign Campaign { get; set; }
        
    }


}

FuNDs/FuNDs/Controllers/DonorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FuNDs.Models;

namespace FuNDs.Controllers
{
    public class DonorsController : Controller
    {
        private FundRaisersDbContext db = new FundRaisersDbContext();

        // GET: Donors
        public ActionResult Index()
        {
            return View(db.Donors.ToList());
        }

        // GET: Donors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donor donor = db.Donors.Find(id);
            if (donor == null)
            {
                return HttpNotFound();
            }
            return View(donor);
        }

        // GET: Donors/Create
        public ActionResult Create()
        {
          //  Donor donor = new Donor();
          //  donor.CampaignId = id;
           
            return View();
        }

        

        // POST: Donors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DonorId,donateAmount,donateDate")] Donor donor)
        {

            if (ModelState.IsValid)
            {
                db.Donors.Add(donor);
                db.SaveChanges();
                
            }
            return View("Pay");
        }

        public ActionResult Pay()
        {
            return View();
        }
        // GET: Donors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donor donor = db.Donors.Find(id);
            if (donor == null)
            {
                return HttpNotFound();
            }
            return View(donor);
        }

        // POST: Donors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DonorId,donateAmount,donateDate")] Donor donor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(donor);
        }

        // GET: Donors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donor donor = db.Donors.Find(id);
            if (donor == null)
            {
                return HttpNotFound();
            }
            return View(donor);
        }

        // POST: Donors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Donor donor = db.Donors.Find(id);
            db.Donors.Remove(donor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FuNDs/FuNDs/Controllers/PaypalController.cs
using FuNDs.Models;
using log4net;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Net;
using System.Web.Configuration;
using System.Web.Mvc;

namespace FuNDs.Controllers
{
    public class PaypalController : Controller
    {
        private FundRaisersDbContext db = new FundRaisersDbContext();

        // GET: Paypal1
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult PaymentWithPaypal(string DonationAmount)
        {

          //  public ActionResult PaymentWithPaypal(int id) { 
     // Donor donor = db.Donors.FirstOrDefault(s => s.DonorId ==);
          //  double amount = donor.DonationAmount;
          //  string amount1 = amount + "";
            //getting the apiContext as earlier
            APIContext apiContext = Configuration.GetAPIContext();
          

            try
            {
                string payerId = Request.Params["PayerID"];

                if (string.IsNullOrEmpty(payerId))
                {
                    //this section will be executed first because PayerID doesn't exist
                    //it is returned by the create function call of the payment class

                    // Creating a payment
                    // baseURL is the url on which paypal sendsback the data.
                    // So we have provided URL of this controller only
                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority +
                                "/Paypal/PaymentWithPayPal?";

                    //guid we are generating for storing the paymentID received in session
                    //after calling the create function and it is used in the payment execution

                    var guid = Convert.ToString((new Random()).Next(100000));

                    //CreatePayment function gives us the payment approval url
                    //on which payer is redirected for paypal account payment

                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid, DonationAmount);

                    //get links returned from paypal in response to Create function call

                    var links = createdPayment.links.GetEnumerator();

                    string paypalRedirectUrl = null;

                    while (links.MoveNext())
                    {
                        Links lnk = links.Current;

                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment
                            paypalRedirectUrl = lnk.href;
                        }
                    }

                    // saving the paymentID in the key guid
                    Session.Add(guid, createdPayment.id);

                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    // This section is executed when we have received all the payments parameters

                    // from the previous call to the function Create

                    // Executing a payment

                    var guid = Request.Params["guid"];

                    var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);

                    if (executedPayment.state.ToLower() != "approved")
                    {
                        return View("Failure");
                    }
                }
            }
            
           catch (Exception ex)
            {
               // Logger.log("Error" + ex.Message);
              // return View("Failure");
            }   
            var txToken = "8R796233JB671434K";
            var authToken = "HlTvz4_zZRExCKYvBHDr8AsNgspBPJIJQ2D97trUfzTk7_qTeY2_6QGlK38";
            var query = string.Format("cmd=_notify-synch&tx={0}&at={1}",
                              txToken, authToken);

            return RedirectToAction("Success"); 
          //  RedirectToAction ("Success");
        }

        private PayPal.Api.Payment payment;

        private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
        {
            var paymentExecution = new PaymentExecution() { payer_id = payerId };
            this.payment = new Payment() { id = paymentId };
            return this.payment.Execute(apiContext, paymentExecution);
        }
        // this is new


        private Payment CreatePayment(APIContext apiContext, string redirectUrl, string DonationAmount)
        {

            //similar to credit card create itemlist and add item objects to it
            var itemList = new ItemList() { items = new List<Item>() };

            itemList.items.Add(new Item()
            {
                name = "Item Name",
                currency = "USD",
                price = DonationAmount,
                quantity = "1",
                sku = "sku"
            });

            var payer = new Payer() { payment_method = "paypal" };

            // Configure Redirect Urls here with RedirectUrls object
            var redirUrls = new RedirectUrls()
            {
                cancel_url = redirectUrl,
                return_url = redirectUrl
            };

            // similar as we did for credit card, do here and create details object
            var details = new Details()
            {
                tax = "0",
                shipping = "0",
                subtotal = DonationAmount
            };

            // similar as we did for credit card, do here and create amount object
            var amount = new Amount()
            {
                currency = "USD",
                total = DonationAmount, // Total must be equal to sum of shipping, tax and subtotal.
                details = details
            };

            var transactionList = new List<Transaction>();
            var invoice = Convert.ToString((new Random()).Next(100000));
            transactionList.Add(new Transaction()
            {
                description = "Transaction description.",
                invoice_number = invoice,
                amount = amount,
                item_list = itemList
            });

            this.payment = new Payment()
            {
                
                intent = "sale",
                payer = payer,
                transactions = transactionList,
                redirect_urls = redirUrls
            };

            // Create a payment using a APIContext
            return this.payment.Create(apiContext);
        }

        // this is end

        //private Payment CreatePayment(APIContext apiContext, string redirectUrl)
        //{

        //    //similar to credit card create itemlist and add item objects to it
        //    var itemList = new ItemList() { items = new List<Item>() };

        //    itemList.items.Add(new Item()
        //    {
        //        name = "Item Name",
        //        currency = "USD",
        //        price = "5",
        //        quantity = "1",
        //        sku = "sku"
        //    });

        //    var payer = new Payer() { payment_method = "paypal" };

        //    // Configure Redirect Urls here with RedirectUrls object
        //    var redirUrls = new RedirectUrls()
        //    {
        //        cancel_url = redirectUrl,
        //        return_url = redirectUrl
        //    };

        //    // similar as we did for credit card, do here and create details object
        //    var details = new Details()
        //    {
        //        tax = "1",
        //        shipping = "1",
        //        subtotal = "5"
        //    };

        //    // similar as we did for credit card, do here and create amount object
        //    var amount = new Amount()
        //    {
        //        currency = "USD",
        //        total = "7", // Total must be equal to sum of shipping, tax and subtotal.
        //        details = details
        //    };

        //    var transactionList = new List<Transaction>();

        //    transactionList.Add(new Transaction()
        //    {
        //        description = "Transaction description.",
        //        invoice_number = "your invoice number",
        //        amount = amount,
        //        item_list = itemList
        //    });

        //    this.payment = new Payment()
        //    {
        //        intent = "sale",
        //        payer = payer,
        //        transactions = transactionList,
        //        redirect_urls = redirUrls
        //    };

        //    // Create a payment using a APIContext
        //    return this.payment.Create(apiContext);
        //}

      


        
        public static class Configuration
        {
            //these variables will store the clientID and clientSecret
            //by reading them from the web.config
            public readonly static string ClientId;
            public readonly static string ClientSecret;

            static Configuration()
            {
                var config = GetConfig();
                ClientId = config["clientId"];
                ClientSecret = config["clientSecret"];
            }

            // getting properties from the web.config
            public static Dictionary<string, string> GetConfig()
            {
                return PayPal.Manager.ConfigManager.Instance.GetProperties();
            }

            private static string GetAccessToken()
            {
                // getting accesstocken from paypal                
                string accessToken = new OAuthTokenCredential
            (ClientId, ClientSecret, GetConfig()).GetAccessToken();

                return accessToken;
            }

            public static APIContext GetAPIContext()
            {
                // return apicontext object by invoking it with the accesstoken

FuNDs/FuNDs/Views/Donors/Create.cshtml
@model FuNDs.Models.Donor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Donor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

      
        @Html.HiddenFor(model => model.DonorId)
        <div class="form-group">
            @Html.LabelFor(model => model.donateAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donateAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donateAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.donateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donateDate, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@*@using (Html.BeginForm("PaymentWithPaypal", "Paypal", FormMethod.Get))
{*@
    

FuNDs/FuNDs/Views/Donors/Delete.cshtml
@model FuNDs.Models.Donor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Donor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.donateAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.donateAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.donateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.donateDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FuNDs/FuNDs/Views/Donors/Details.cshtml
@model FuNDs.Models.Donor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Donor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.donateAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.donateAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.donateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.donateDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DonorId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FuNDs/FuNDs/Views/Donors/Edit.cshtml
@model FuNDs.Models.Donor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Donor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DonorId)

        <div class="form-group">
            @Html.LabelFor(model => model.donateAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donateAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donateAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.donateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.donateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.donateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FuNDs/FuNDs/Views/Donors/Index.cshtml
@model IEnumerable<FuNDs.Models.Donor>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.donateAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.donateDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.donateAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.donateDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DonorId }) |
            @Html.ActionLink("Details", "Details", new { id=item.DonorId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.DonorId })
        </td>
    </tr>
}

</table>

FuNDs/FuNDs/Views/Donors/Pay.cshtml
@model FuNDs.Models.Donor


    <div class="text-center">
        <section id="sign-up" class="container">

            @using (Html.BeginForm("PaymentWithPaypal", "Paypal", FormMethod.Get))
            {


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <level class="container text-center" style="margin-left:5px; color:forestgreen;">                    
                        <h4 ><b>Donate</b></h4>                    
                    </level>
                   


                    <div class="form-group">
                        @Html.LabelFor(model => model.DonationAmount, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.DonationAmount, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DonationAmount, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">

                        <label class="col-md-3 control-label">Date: </label>
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.donateDate, new { htmlAttributes = new { @class = "form-control", @placeholder = "Password" } })
                            @Html.ValidationMessageFor(model => model.donateDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @*<div class="form-group">
                        @Html.LabelFor(model => model.donateDate, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.donateDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.donateDate, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                    <div class="form-group">
                        <div class="form-group">
                            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">

                        </div>
                    </div>

                    }

</section>
    </div>



    @*<div class="text-center">
        <section id="sign-up" class="container">
            @using (Html.BeginForm("PaymentWithPaypal", "Paypal", FormMethod.Get))
            {
            <div class="form-group">
                @Html.LabelFor(model => model.donateAmount, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9" id="payform">
                    @Html.EditorFor(model => model.donateAmount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.donateAmount, "", new { @class = "text-danger" })
                </div>
            </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.donateDate, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9" id="payform">
                        @Html.EditorFor(model => model.donateDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.donateDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p>
                    <add type="hidden" name="returnUrl" value="http://localhost:19377/Thankyou.html" />
                    <div class="form-group">
                        <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                        @*<input type="submit" class="btn btn-default" />*@